### ISSUE TITLE
Unable to Set num_slots Directly

### ISSUE THREAD

**Issue by afiff2** [lucidrains/soft-moe-pytorch#7]
The assertion  `assert exists(seq_len) ^ exists(num_slots), 'either seq_len, or num_slots must be passed into SoftMoE'`
restricts setting num_slots directly when seq_len is also set. I would like to set num_slots directly, but this assertion prevents me from doing so if seq_len is set.
Therefore, I set num_slots only, causing seq_len to be None. Consequently, the line 
`num_slots = default(num_slots, seq_len // num_experts)`
fails to execute properly.

**Comment by lucidrains** [comment]
@afiff2 oh sure, yea my bad
